:global:
  componentName: {{ cookiecutter.name }}
  githubUrl: {{ cookiecutter.github_url }}
  feature_goldenTests: true

docs/antora.yml:
  name: {{ cookiecutter.slug }}
  title: {{ cookiecutter.name }}
