:global:
  componentName: {{ cookiecutter.name }}
  githubUrl: {{ cookiecutter.github_url }}

LICENSE:
  year: {{ cookiecutter.copyright_year }}

docs/antora.yml:
  name: {{ cookiecutter.slug }}
  title: {{ cookiecutter.name }}
