name: Pull Request
on:
  pull_request:
    branches:
      - master

env:
  COMPONENT_NAME: {{ cookiecutter.slug }}

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - lint_jsonnet
          - lint_yaml
          - lint_adoc
    steps:
      - uses: actions/checkout@v2
      - name: Run {% raw %}${{ matrix.command }}{% endraw %}
        run: make {% raw %}${{ matrix.command }}{% endraw %}
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snow-actions/eclint@v1.0.1
        with:
          args: 'check'
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
    steps:
      - uses: actions/checkout@v2
        with:
          path: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
      - name: Compile component
        run: make test
{%- if cookiecutter.add_golden == "y" %}
  golden:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
    steps:
      - uses: actions/checkout@v2
        with:
          path: {% raw %}${{ env.COMPONENT_NAME }}{% endraw %}
      - name: Golden diff
        run: make golden-diff
{%- endif %}
