name: PyPI release

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry install
      - name: inject version
        run: make inject-version
      - name: build commodore
        run: poetry build
      - name: publish to pypi
        if: startsWith(github.ref, 'refs/tags/v')
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
