name: PyPI release

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - master

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
      - name: Setup poetry environment
        run: |
          pip install poetry
          poetry install
      - name: Inject package versions to action env
        run: make inject-version
      - name: Set Python package version for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: poetry version "${PYVERSION}"
      - name: Set Python package version
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: |
          poetry version "${PYVERSION}.dev${GITHUB_RUN_NUMBER}"
      - name: Build Python package
        run: poetry build
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      - name: Publish to TestPyPI
        if: "!startsWith(github.ref, 'refs/tags/v')"
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry publish -r test-pypi -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }}
